language: java
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email: false

script: mvn clean package -DskipTests=true

after_success:
- bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)
